apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinyolly-redis
  labels:
    app: tinyolly-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tinyolly-redis
  template:
    metadata:
      labels:
        app: tinyolly-redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        command: ["redis-server", "--port", "6579", "--maxmemory", "256mb", "--maxmemory-policy", "allkeys-lru"]
        ports:
        - containerPort: 6579
---
apiVersion: v1
kind: Service
metadata:
  name: tinyolly-redis
spec:
  selector:
    app: tinyolly-redis
  ports:
    - protocol: TCP
      port: 6579
      targetPort: 6579
